# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21a520c2009610071a79a37e514ba06db011b9fc017c17a7458afe3f2a6e86868fca6cdc3983e89f5a1323d27438fa40e546c344bc790c21e2e58ef03462315a

test:
  secret_key_base: 97abb084ba049d1ad80a86313e52c802d122d4cc9a64124621b0e7f67930eaa0351a7b82f6398f1e272dfef87b82d71dc79a3056da87b7176ab69bbaad4badec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
