# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae38ac893525004b56026eea5200d0ca0e1cbd7f9a96e3ae941022ad38206663c06c289992882f0003fdb8d49fd3154921d78c67b553d756f7bdce759b2f1ba3

test:
  secret_key_base: 6c8be9632b36cf8991974dd2358039c00bad957b588b1d363492faae7b675c913e430c1c0b94135fbf4bba3193a853b361514c54442d3cd49b446b7eb49d8a34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
